# Generated by Django 2.2.1 on 2020-12-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Market',
        ),
        migrations.AddField(
            model_name='item',
            name='market_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
