# Generated by Django 2.2.1 on 2020-12-15 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodies_app', '0003_auto_20201214_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='market_id',
            new_name='market',
        ),
    ]
